FROM ubuntu:{{ docker_image_version | default('latest') }} AS install_phase

RUN apt-get update

RUN apt-get install -y g++ openjdk-8-jdk python3-dev python3-pip
RUN python3 -m pip install --upgrade pip
RU