FROM centos:7

RUN yum update -y
RUN yum install --assumeyes gcc-c++ python3 python3-devel python3-pip java-1.8.0-openjdk-devel make diffutils
RUN python3 -m pip install --upgrade pip
RUN python3 -m pip install konlpy

RUN yum install --assumeyes curl git
RUN curl -s https://raw.githubusercontent.com/konlpy/konlpy/master/scripts/mecab.sh | bash

RUN yum install -